### ISSUE TITLE
xivFaderPlugin tanks performance.

### ISSUE THREAD

**Issue by Maxunit** [shdwp/xivFaderPlugin#1] opened 2021-10-20 18:56 UTC
I just installed xivFaderPlugin and somehow, for some reason, it instantly tanks my performance from locked 60 FPS down to 45 FPS or even lower.  No idea why and what the reason might be.

EDIT: Somehow...it fixed itself, for now, after restarting the game, but before that it tanked the fps whenever I activated/enabled it.

EDIT 2:

And again...it heavily decreases performance within minutes.

**Comment by shdwp** [comment] 2021-10-20 22:28
So what you are saying is that it's fine for a while after you enable it, but then it slows things down after a while? Is it fixed by disabling\enabling the plugin? Or only game restart?

**Comment by shdwp** [comment] 2021-10-21 11:27
Can you post dalamud logs? `%APPDATA%/XIVLauncher/dalamud.log`

**Comment by Maxunit** [comment] 2021-10-21 13:53
I checked the dalamud.log myself and after installing the plugin, there is no indication of anything particular happening. Penumbra loading some modded files, the orchestrion plugin telling me about song changes and that's it.

The only thing that happened inbetween was the game going into AFK-Camera Mode after 5 minutes, since I have set the game to do that whenever I go afk for a bit longer. It just happened again and the game went from the 15 FPS in AFK-Cam Mode to only 40 FPS and as soon as I disable the plugin, the FPS jumps back to the intended stable and capped 60 FPS.

**Comment by Maxunit** [comment] 2021-10-24 00:39
I didn't have the time today to test it, but something I'd check would be to disable any active "UI Tweaks" options, if one has SimpleTweaks installed and any of those active, to see, if that fixes it (and then go one by one to see which ones cause problems. Kind of related: FaderPlugin also breaks the Combo Timer feature from SimpleTweaks, at least temporarily. Causes the Combo Timer element to be displayed, even if it should be hidden and therefor it shows up corrupted.)

**Comment by shdwp** [comment] 2021-10-24 01:11
It's weird since I also use lots of stuff from SimpleTweaks and I never been able to reproduce the slowdown. Each time I suspect it disabling the plugin changes nothing.

I'll test with combo timer tomorrow to see whether anything changes.

**Closed as completed** 2021-10-25 10:33 UTC
